package net.mark.helg.entity.client.helgerite;


import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class HelgeriteAnimations {


	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(12f).looping()
			.addAnimation("wing2",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wing2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.33333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.625f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.91667f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.58333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.91667f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.125f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.45833f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.70833f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.04167f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.5f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.83333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.25f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.58333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.33333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.625f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.08333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.33333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.66667f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.95833f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.20833f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.58333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.83333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.08333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.33333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.58333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.83333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.16667f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.41667f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.75f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(10.08333f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(10.45833f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(10.70833f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.08333f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.41667f, KeyframeAnimations.degreeVec(0f, 0f, -25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.66667f, KeyframeAnimations.degreeVec(0f, 0f, 100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.91667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wing1",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("wing1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.33333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.58333f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.875f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.25f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.66667f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.20833f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.54167f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.79167f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.125f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.58333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.91667f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.33333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.66667f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.08333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.41667f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.625f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.25f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.58333f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.04167f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.29167f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.5f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.75f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.08333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.33333f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.58333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.75f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.08333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.41667f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.75f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(10.08333f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(10.375f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(10.70833f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.33333f, KeyframeAnimations.degreeVec(0f, 0f, 25.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.58333f, KeyframeAnimations.degreeVec(0f, 0f, -100f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(11.91667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(12f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.58333f, KeyframeAnimations.degreeVec(0f, 2.5f, 1.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.70833f, KeyframeAnimations.degreeVec(1.25f, 0f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(8.91667f, KeyframeAnimations.degreeVec(-2.5f, -1.5f, -2.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
}
