package net.mark.helg.entity.client.helgerite;

import net.minecraft.client.render.entity.animation.*;

public class HelgeriteAnimations {


	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.create(12f).looping()
			.addBoneAnimation("wing2",
					new Transformation(Transformation.Targets.MOVE_ORIGIN,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("wing2",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.625f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.91667f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.58333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.91667f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.125f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.45833f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.70833f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.04167f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.5f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.83333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(4.25f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(4.58333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5.33333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5.625f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6.08333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6.33333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6.66667f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6.95833f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.20833f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.58333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.83333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.08333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.33333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.58333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.83333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9.16667f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9.41667f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9.75f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(10.08333f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(10.45833f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(10.70833f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.08333f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.41667f, AnimationHelper.createRotationalVector(0f, 0f, -25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.66667f, AnimationHelper.createRotationalVector(0f, 0f, 100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.91667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("wing1",
					new Transformation(Transformation.Targets.MOVE_ORIGIN,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("wing1",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.58333f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(0.875f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(1.66667f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.20833f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.54167f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.79167f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.125f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.58333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3.91667f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(4.33333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(4.66667f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5.08333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5.41667f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5.625f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6.25f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6.58333f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.04167f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.29167f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.5f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(7.75f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.08333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.33333f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.58333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.75f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9.08333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9.41667f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9.75f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(10.08333f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(10.375f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(10.70833f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.33333f, AnimationHelper.createRotationalVector(0f, 0f, 25.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.58333f, AnimationHelper.createRotationalVector(0f, 0f, -100f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(11.91667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("body",
					new Transformation(Transformation.Targets.MOVE_ORIGIN,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(9f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(12f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC)))
			.addBoneAnimation("body",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(2.58333f, AnimationHelper.createRotationalVector(0f, 2.5f, 1.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(5.70833f, AnimationHelper.createRotationalVector(1.25f, 0f, -1.25f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(8.91667f, AnimationHelper.createRotationalVector(-2.5f, -1.5f, -2.5f),
									Transformation.Interpolations.CUBIC),
							new Keyframe(12f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.CUBIC))).build();
}
